version: '2'
services:

  cornelia-service:
    restart: always
    image: repdom/docker-cornelia-app
    environment:
      - SERVER_PORT=8080
    networks:
      - cornelia
    depends_on:
      - mariadb
    ports:
      - "8080"
  mariadb:
    container_name: mariadb
    restart: always
    image: mariadb:10.2
    ports:
      - 3307:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: encuesta
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - cornelia
volumes:
  mysql_db:

networks:
  cornelia:
