version '2'

services:
  cornelia-service:
    restart: always
    image: repdom/docker-cornelia-app
    environment:
      - SERVER_PORT=8080
    depends_on:
      - mysqldb
    ports:
      - "8080"
  cornelia2-service:
    restart: always
    image: repdom/docker-cornelia-app
    environment:
      - SERVER_PORT=8081
    depends_on:
      - mysqldb
    ports:
      - "8081"
  cornelia3-service:
    restart: always
    image: repdom/docker-cornelia-app
    environment:
      - SERVER_PORT=8082
    depends_on:
      - mysqldb
    ports:
      - "8082"
  ha-proxy:
    restart: always
    depends_on:
      - cornelia-service
      - cornelia2-service
      - cornelia3-service
    image: haproxy:2.0.2
    volumes:
      - ./etc:/usr/local/etc/haproxy
    ports:
      - "80:80"
  mysqldb:
    container_name: mysql
    restart: always
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: encuesta
    volumes:
      - mysql_db:/var/lib/mysql
volumes:
  mysql_db:

networks:
  default:
    external:
      name: docker_default