version: '2'
services:

  cornelia-service:
    restart: always
    image: repdom/docker-cornelia-app
    environment:
      - SERVER_PORT=8080
    depends_on:
      - mariadb
    ports:
      - "8080"
  cornelia2-service:
    restart: always
    image: repdom/docker-cornelia-app
    environment:
      - SERVER_PORT=8081
    depends_on:
      - mariadb
    ports:
      - "8081"
  cornelia3-service:
    restart: always
    image: repdom/docker-cornelia-app
    environment:
      - SERVER_PORT=8082
    depends_on:
      - mariadb
    ports:
      - "8082"
  ha-proxy:
    restart: always
    depends_on:
      - cornelia-service
      - cornelia2-service
      - cornelia3-service
    image: haproxy:2.0.2
    volumes:
      - ./etc:/usr/local/etc/haproxy
    ports:
      - "81:80"
  mariadb:
    container_name: mariadb
    restart: always
    image: mariadb:10.2
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: RDsIdEe1865@
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: encuesta
    volumes:
      - mysql_db:/var/lib/mysql
volumes:
  mysql_db:

networks:
  default:
    external:
      name: docker_default