version: '2'
services:

  cornelia-service:
    restart: always
    image: repdom/docker-cornelia-app
    environment:
      - SERVER_PORT=8080
      - spring.datasource.url=jdbc:mysql://mariadb:3306/encuesta?useUnicode=true&characterEncoding=UTF-8
    networks:
      - cornelia
    ports:
      - 8080:8080
    depends_on:
      - mariadb
  cornelia2-service:
    restart: always
    image: repdom/docker-cornelia-app
    environment:
      - SERVER_PORT=8081
      - spring.datasource.url=jdbc:mysql://mariadb:3306/encuesta?useUnicode=true&characterEncoding=UTF-8
    networks:
      - cornelia
    depends_on:
      - mariadb
    ports:
      - 8081:8081
  cornelia3-service:
    restart: always
    image: repdom/docker-cornelia-app
    environment:
      - SERVER_PORT=8082
      - spring.datasource.url=jdbc:mysql://mariadb:3306/encuesta?useUnicode=true&characterEncoding=UTF-8
    networks:
      - cornelia
    depends_on:
      - mariadb
    ports:
      - 8082:8082
  ha-proxy:
    restart: always
    networks:
      - cornelia
    depends_on:
      - cornelia-service
      - cornelia2-service
      - cornelia3-service
    image: haproxy:2.0.2
    volumes:
      - ./etc:/usr/local/etc/haproxy
    ports:
      - 81:80
  mariadb:
    restart: always
    image: mariadb:10.2
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD:  RDsIdEe1865@
      MYSQL_ROOT_HOST:  "%"
      MYSQL_DATABASE: encuesta
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - cornelia
volumes:
  mysql_db:

networks:
  cornelia:
