version: '2'
services:

  cornelia-service:
    restart: always
    image: repdom/docker-cornelia-app
    environment:
      - SERVER_PORT=8080
      - spring.datasource.url=jdbc:mysql://mariadb:3307/encuesta?useUnicode=true&characterEncoding=UTF-8
    networks:
      - cornelia
    ports:
      - 8080:8080
    depends_on:
      - mariadb
  mariadb:
    restart: always
    image: mariadb:10.2
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD:  RDsIdEe1865@
      MYSQL_ROOT_HOST:  "%"
      MYSQL_DATABASE: encuesta
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - cornelia
volumes:
  mysql_db:

networks:
  cornelia:
