version: '3.7'
services:

  cornelia-service:
    restart: always
    image: repdom/docker-cornelia-app
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mariadb-cornelia:3307/encuesta
      - spring.datasource.username=root
      - spring.datasource.password=
    networks:
      - cornelia
    depends_on:
      - mariadb-cornelia
  mariadb-cornelia:
    restart: always
    image: mysql:5.7.26
    ports:
      - 3307:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
      - MYSQL_USER=root
      - MYSQL_DATABASE=encuesta
    volumes:
      - ~/dato_mysql_compose:/var/lib/mysql
    networks:
      - cornelia
networks:
  cornelia:
